services:
  - type: web
    name: 3c-cost-estimator
    env: python
    plan: free
    buildCommand: python -m pip install --upgrade pip && python -m pip install -r requirements.txt
    startCommand: python -m streamlit run app.py --server.address 0.0.0.0 --server.port $PORT
    autoDeploy: false

